id: I0FC8F529
legacy_id: P006930
ocr_import_info:
  bdrc_scan_id: W1KG14815
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T21:26:37'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T05:19:02.045118+00:00'
last_modified: 2022-08-27 13:19:38.856965
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG14815
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG14815
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གྲུབ་ཐོབ་ཉག་རེ་སེ་བོའི་སྐྱེས་རབས་རྣམ་ཐར་མ་འོང་ལུང་བསྟན་ཞལ་ཆེམས་ཉམས་མགུར།
  author: གྲུབ་ཐོབ་ཉག་སེ་བ།
statistics:
  ocr_word_mean_confidence_index: 0.9289259642134643
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG14847:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14847
      total_pages: 294
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG14847.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9289259642134643
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
